services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "3009:3009"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/wa-bot
    depends_on:
      - mongo
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: npx nodemon server.js

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    command: npx nodemon bot/index.js
    volumes:
      - ./bot:/app/bot
      - ./session:/app/bot/session
    working_dir: /app/bot
    depends_on:
      - backend

  frontend-dev:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend

volumes:
  mongo-data:
