FROM node:18

WORKDIR /app/backend

COPY package*.json ./
RUN npm install

# ⬇️ Install nodemon global
RUN npm install -g nodemon

COPY . .

EXPOSE 3009

# Jalankan menggunakan nodemon (pastikan script `api` = "nodemon server.js")
CMD ["npm", "run", "api"]
